* Total [57/72]
 - [X] Что такое регрессия величины Y по величине X и что представляет собой модель линейной регрессии**
 - [X] Что представляет собой оценка по методу наименьших квадратов*
 - [X] Геометрический смысл метода наименьших квадратов*
 - [X] Какие функции параметра модели линейной регрессии допускают несмещенное оценивание.
 - [X] Теорема Гаусса-Маркова*
 - [X] Что такое нормальные уравнения*
 - [X] Определение порядковых статистик и рангов*
 - [X] Что такое выборочная функция распределения**
 - [ ] Что представляет собой случайная величина, функция распределения которой – выборочная функция распределения*
 - [X] Теорема Гливенко-Кантелли**
 - [X] Теорема Колмогорова*
 - [X] Построение доверительной области для теоретической функции распределения с помощью теоремы Колмогорова
 - [X] Что называется выборочной характеристикой случайной величины. Примеры (выборочные моменты, выборочные квантили)*
 - [X] Виды сходимости случайных величин и распределений
 - [X] Метод построения доверительных эллипсоидов для параметров линейной регрессии
 - [ ] Постановка задачи однофакторного дисперсионного анализа, F-критерий проверки однородности наблюдений в предположении нормальности.
 - [ ] Построение Хи-квадрат, Стьюдента, Фишера-Снедекора распределений с помощью выборки из нормального закона**
 - [X] Лемма Фишера**
 - [X] Что такое функция потерь, риск
 - [X] Какая оценка называется состоятельной**
 - [X] Какая оценка называется несмещенной, что такое смещение*
 - [X] Какая оценка называется асимптотически нормальной*
 - [X] Определение несмещенной оценки с равномерно минимальной дисперсией*
 - [X] Как используются теорема Рао-Блэкуэлла-Колмогорова и теорема Лемана-Шеффе при построении НРМД-оценки.
 - [ ] Неравенство Гельдера
 - [X] Что представляет собой простая регрессионная модель
 - [X] Что представляет собой полиномиальная регрессионная модель
 - [X] Связь между различными видами сходимости случайных величин и распределений
 - [X] Метод максимального правдоподобия**
 - [X] Определение достаточной статистики*
 - [X] Теорема факторизации Неймана-Фишера*
 - [ ] Какое известное двумерное распределение обладает свойством линейности регрессии (одной компоненты по другой)
 - [ ] Каким свойством обладают однопараметрические семейства распределений для которых существует эффективная оценка.
 - [ ] Определение экспоненциального семейства
 - [X] Определение полной достаточной статистики и подчиненной статистики
 - [ ] В чем состоит свойство асимптотической нормальности оценки максимального правдоподобия
 - [X] Что такое функция правдоподобия*
 - [X] Что представляет собой семейство распределений Пуассона*
 - [ ] Какие распределения называются показательными*
 - [X] Определение регулярного эксперимента и информации Фишера**
 - [X] Неравенство Рао-Крамера**
 - [X] Какая оценка называется эффективной по Фишеру*
 - [ ] Центральная предельная теорема Леви*
 - [X] Что называется доверительным интервалом уровня α*
 - [ ] Законы больших чисел
 - [X] Понятие асимптотического доверительного интервала
 - [X] Метод построения асимптотических доверительных интервалов на базе асимптотически нормальной оценки
 - [X] Постановка задачи ПСГ, верное решение и ошибки (таблица)**
 - [X] Статистический критерий, доверительная, критическая области и область сомнений*
 - [X] Выражение вероятностей ошибок в терминах критерия**
 - [X] Лемма Неймана-Пирсона**
 - [ ] Проверка гипотез о параметрах линейной регрессионной модели (F-критерий)*
 - [X] Критерий проверки гипотезы согласия о среднем нормального закона при неизвестной дисперсии
 - [X] Критерий проверки независимости хи-квадрат
 - [ ] Критерий проверки однородности двух независимых выборок из нормального закона с равными (неизвестными) дисперсиями
 - [ ] Что такое статистика критерия и как она используется при построении нерандомизованного (асимптотического) критерия**
 - [X] Критерий согласия Колмогорова*
 - [ ] Постановка задачи двухфакторного дисперсионного анализа, главные эффекты и взаимодействия
 - [X] Какое распределение называется мультиномиальным и его связь с хи-квадрат критерием.
 - [X] Критерий хи-квадрат для проверки простой гипотезы согласия**
 - [X] Критерий хи-квадрат для проверки сложной параметрической гипотезы согласия*
 - [X] Какой критерий называется наиболее мощным
 - [X] Что определяет значение критерия и какой критерий называется нерандомизованным
 - [X] Выражение ошибки 1-го рода и мощности в терминах критерия. В чем отличие между ними.
 - [X] Что называется ошибкой I-го рода**
 - [X] Что называется ошибкой II-го рода и мощностью критерия**
 - [X] Что такое уровень значимости критерия, критическая и доверительная области**
 - [X] Что такое распределение Стьюдента*
 - [X] Характеристические функции: определение и основные свойства
 - [X] Что такое гамма распределение, его свойства*
 - [X] Что представляет собой двухпараметрическое семейство нормальных распределений**
 - [X] Построение доверительных интервалов для параметров линейной регрессионной модели в предположении нормальности*.
